knpu_oauth2_client:

    clients:

        facebook:
            # must be "facebook" - it activates that type!
            type: facebook
            # add and set these environment variables in your .env files
            client_id: '%env(FB_ID)%'
            client_secret: '%env(FB_SECRET)%'
            # a route name you'll create
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v2.12
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
        
        google:
            # must be "facebook" - it activates that type!
            type: google
            # add and set these environment variables in your .env files
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: connect_google_check
            redirect_params: {}
                   
            # whether to check OAuth2 "state": defaults to true
            # use_state: true